name: 'Regex on Repo'
description: 'Runs regex on repositories, on the cloud!'
branding:
  icon: book
  color: green
  
inputs:
  github:
    description: 'The owner and repository that owns the file.'
    required: true
  ref:
    description: 'The reference to use for getting the file, can be a commit sha, branch name, or tag.'
    required: true
  token:
    description: 'A github token that has read access to the repository.'
    required: true
  regex:
    description: 'The regex match string.'
    required: true
  file:
    description: 'The directory to the file to read, relative to the root of the specified repository.'
    required: true
  debug:
    description: 'Debug output toggle, will output to the console all the matches with every group. false by default.'
    required: false
    
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6'

    - name: Nuget
      uses: nuget/setup-nuget@v1

    - name: Run
      shell: bash
      env:
        _github: ${{ inputs.github}}
        _regex: ${{ inputs.regex }}
        _refsha: ${{ inputs.refsha }}
        _token: ${{ inputs.token }}
        _file: ${{ inputs.file }}
        _debug: ${{ inputs.debug}}
      run: |
        dotnet restore
        dotnet build
        dotnet run