name: Test Windows

on:
  push:

jobs:
  regex:
    runs-on: windows-latest
   
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Regex On Repo
      id: regex
      uses: ./
      with:
        github: ${{ github.repository }}
        ref:  'development'
        token: ${{ secrets.GITHUB_TOKEN }}
        regex: '`([^`\W]+)`'
        file: 'README.md'
        debug: true
